apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: block-privileged-containers
  namespace: app
spec:
  validationFailureAction: Enforce
  rules:
    - name: block-privileged
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Privileged containers are not allowed"
        pattern:
          spec:
            containers:
              - securityContext:
                  privileged: false
